# Generated by Django 4.0.5 on 2022-12-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_students_department'),
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
