# Generated by Django 4.0.5 on 2022-12-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_account_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='department',
        ),
    ]
