# Generated by Django 4.0.5 on 2023-01-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_students_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(default='inactive', max_length=100),
        ),
    ]
